services:
  app:
    restart: always
    image: $REGISTRY_URL/$REGISTRY_USERNAME/$APP_NAME:latest
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    volumes:
      - ./forms.db:/app/forms.db  
